export const endpoints = {
  version: '/v1',
  ping: '/ping',
  exchange: '/exchanges',
  count: '/count',
  market: '/markets',
  status: '/status',
  trade: '/trades',
  lastTrade: '/lastTrade',
  aggregate: '/aggregates',
  lastAggregate: '/lastAggregate',
  currentPrice: '/currentPrice',
  snapshot: '/snapshot',
  orders: '/orders',
}
